python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m CN -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m CE -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m VVAA -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m VEAA -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m EVAA -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m EEAA -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m DE -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m WK2 -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m WK3 -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m JC -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m COS -pt 400;
python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m RA -pt 400;
# python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,DBLP-Co-authorship,email-Eu,iAB_RBC_283,iJO1366,yuecai,CoreComplex -r 10 -m RWR -rp 0.15 -pt 400;
# python main.py -d cat-edge-music-blues-reviews,chuancai,Cora-Co-citation,Cora-Co-reference,iAB_RBC_283,iJO1366,yuecai -r 10 -m SKatz -pt 400;
# python main.py -d DBLP-Co-authorship -r 10 -m SKatz -pt 400;
# python main.py -d email-Eu -r 10 -m SKatz -pt 400;
# python main.py -d CoreComplex -r 10 -m SKatz -pt 400;